// Test and benchmark of the safegcd inverse (mcl/include/mcl/invmod.hpp):
// the C++ versions (twos::exec<N, W> with W = N or N + 1) and the
// LLVM versions (llvm_invMod / llvm_invMod_br generated by gen_ff.py -invMod
// -inv_helpers into src/bench_llvm.ll). Built as bin/invmod_test.exe by the
// Makefile (make invmod_test TYPE=...); -mode 1 tests, 2 benchmarks.
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <vector>
#include <chrono>
#include <mcl/fp_def.hpp>
#include <mcl/invmod.hpp>
#include <cybozu/xorshift.hpp>
#include <cybozu/option.hpp>

using namespace mcl;
using namespace mcl::fp;

extern "C" {
	const uint8_t* llvm_get_prime();
	// safegcd inverse (the LLVM version of twos::exec<N, W>): y[N] =
	// x[N]^-1 mod p (plain representation, y = x allowed); im is
	// mcl::inv::InvModT<N> (W = N + 1 if im.wide). Weak so that bench_llvm.ll
	// built without -invMod still links
	__attribute__((weak)) void llvm_invMod(uint64_t *y, const uint64_t *x, const uint64_t *im);
	// the same with the eta < 0 swap of divsteps by a branch instead of selects
	__attribute__((weak)) void llvm_invMod_br(uint64_t *y, const uint64_t *x, const uint64_t *im);
	// the helpers of llvm_invMod (exported by -inv_helpers for checkInvMod);
	// the same signatures as mcl::inv::{divsteps_n_matrix, twos::update_fg,
	// twos::update_de} with t = {u, v, q, r}
	__attribute__((weak)) uint64_t llvm_inv_divsteps(uint64_t *t, uint64_t eta, uint64_t f, uint64_t g);
	__attribute__((weak)) uint64_t llvm_inv_divsteps_br(uint64_t *t, uint64_t eta, uint64_t f, uint64_t g);
	__attribute__((weak)) void llvm_inv_update_fg(uint64_t *f, uint64_t *g, const uint64_t *t);
	__attribute__((weak)) void llvm_inv_update_de(uint64_t *d, uint64_t *e, const uint64_t *t, const uint64_t *im);
}

// Time one measurement. op(k) runs the operation on stream k. P streams:
// P=1 is a serial dependency chain (latency); P=4 runs independent chains
// (throughput). (the same as test/bench.cpp)
template<class Op>
static double measure(Op op, size_t P, size_t loop)
{
	size_t m = loop / P;
	for (size_t i = 0; i < m / 10; i++) for (size_t k = 0; k < P; k++) op(k); // warmup
	auto t0 = std::chrono::steady_clock::now();
	for (size_t i = 0; i < m; i++) for (size_t k = 0; k < P; k++) op(k);
	auto t1 = std::chrono::steady_clock::now();
	return std::chrono::duration<double, std::nano>(t1 - t0).count() / (m * P);
}

void printRow(const char *name, const char *mode, const std::vector<double>& v) {
	printf("%-7s %-11s", name, mode);
	for (size_t i = 0; i < v.size(); i++) {
		char buf[64];
		if (v[i] == 0) snprintf(buf, sizeof(buf), "-"); // absent impl
		else if (i == 0) snprintf(buf, sizeof(buf), "%.3f", v[i]); // base
		else snprintf(buf, sizeof(buf), "%.3f(%.2fx)", v[i], v[i] / v[0]);
		printf(" %15s", buf);
	}
	printf("\n");
}

static const int TEST_MODE = 1<<0;
static const int BENCH_MODE = 1<<1;

// ---- invMod (safegcd, mcl/include/mcl/invmod.hpp) ----
typedef void (*InvModOp)(uint64_t*, const uint64_t*, const uint64_t*);
typedef uint64_t (*DivstepsOp)(uint64_t*, uint64_t, uint64_t, uint64_t);

// The two's complement C++ version (the former mcl::inv::twos, kept here as
// the reference of the LLVM version): f, g, d, e are W-unit two's complement
// values (W = N, or N + 1 (wide) if -2M < d, e < M does not fit in signed N
// units), the signed products are the unsigned mulUnit plus sign corrections.
// mcl::inv itself is now the signed-limb (signed62/signed30) version.
namespace twos {

// the parameter block of the LLVM version (lowM, Mi, M[N+1] zero-extended)
template<int N>
struct Param {
	Unit lowM;
	Unit Mi; // M^-1 mod 2^mcl::inv::modL
	Unit M[N + 1];
	bool wide;
};

template<int N>
bool initParam(Param<N>& p, const mpz_class& M)
{
	bool b;
	gmp::getArray(&b, p.M, N, M);
	if (!b) return false;
	p.M[N] = 0;
	p.lowM = p.M[0];
	mpz_class inv;
	mpz_class mod = mpz_class(1) << mcl::inv::modL;
	gmp::invMod(inv, M, mod);
	p.Mi = gmp::getUnit(inv, 0) & mcl::inv::MASK;
	p.wide = gmp::getBitSize(M) > mcl::UnitBitSize * N - 2;
	return true;
}


inline Unit signMask(Unit x)
{
	return Unit(0) - (x >> (mcl::UnitBitSize - 1));
}

/*
	z[W+1] = x[W] * a + y[W] * b (x, y : two's complement, a, b : signed units)
	The result fits in W+1 units, so the low W+1 units of the unsigned
	products are corrected as
	x a = x_u a_u - [x < 0] (a_u << (W mcl::UnitBitSize)) - [a < 0] (x_u << mcl::UnitBitSize)
	mod 2^((W+1) mcl::UnitBitSize) (the same for y b). The two (x_u << mcl::UnitBitSize)
	corrections are summed before the subtraction (mod 2^(W mcl::UnitBitSize) suffices).
*/
template<int W>
void mulAdd2(Unit *z, const Unit *x, Unit a, const Unit *y, Unit b)
{
	z[W] = mcl::bint::mulUnitT<W>(z, x, a);
	z[W] += mcl::bint::mulUnitAddT<W>(z, y, b);
	z[W] -= (a & signMask(x[W - 1])) + (b & signMask(y[W - 1]));
	const Unit ma = signMask(a);
	const Unit mb = signMask(b);
	Unit s[W], t[W];
	for (int i = 0; i < W; i++) {
		s[i] = x[i] & ma;
		t[i] = y[i] & mb;
	}
	mcl::bint::addT<W>(s, s, t);
	mcl::bint::subT<W>(z + 1, z + 1, s);
}

// z[W+1] += x[W] * y (x >= 0 (M), y : signed unit)
template<int W>
void mulAddNonNeg(Unit *z, const Unit *x, Unit y)
{
	z[W] += mcl::bint::mulUnitAddT<W>(z, x, y);
	const Unit m = signMask(y);
	Unit t[W];
	for (int i = 0; i < W; i++) t[i] = x[i] & m;
	mcl::bint::subT<W>(z + 1, z + 1, t);
}

// y[W] = x[W+1] >> mcl::inv::modL (arithmetic shift ; the result fits in W units)
template<int W>
void shr(Unit *y, const Unit *x)
{
	// the top 3 bits of x[W] must be equal so that the result fits in W units
	assert((x[W] >> (mcl::UnitBitSize - 3)) == 0 || (x[W] >> (mcl::UnitBitSize - 3)) == 7);
	for (int i = 0; i < W; i++) {
		y[i] = (x[i] >> mcl::inv::modL) | (x[i + 1] << (mcl::UnitBitSize - mcl::inv::modL));
	}
}

template<int W>
void update_fg(Unit *f, Unit *g, const mcl::inv::Quad& t)
{
	Unit f1[W + 1], g1[W + 1];
	mulAdd2<W>(f1, f, t.u, g, t.v);
	mulAdd2<W>(g1, f, t.q, g, t.r);
	shr<W>(f, f1);
	shr<W>(g, g1);
}

/*
	d = (d u + e v + sd M) >> mcl::inv::modL, e = (d q + e r + se M) >> mcl::inv::modL
	sd = ud - ((Mi cd) mod 2^mcl::inv::modL) (in (ud - 2^mcl::inv::modL, ud], ud = u [d < 0] + v [e < 0],
	cd = the low unit of d u + e v + M ud), so d u + e v + sd M = 0 mod 2^mcl::inv::modL and
	-2M < d, e < M is kept (cf. secp256k1_modinv64_update_de_62).
*/
template<int N, int W>
void update_de(const Param<N>& im, Unit *d, Unit *e, const mcl::inv::Quad& t)
{
	const Unit *M = im.M;
	const Unit md = signMask(d[W - 1]);
	const Unit me = signMask(e[W - 1]);
	Unit ud = (t.u & md) + (t.v & me);
	Unit ue = (t.q & md) + (t.r & me);
	Unit d1[W + 1], e1[W + 1];
	mulAdd2<W>(d1, d, t.u, e, t.v);
	mulAdd2<W>(e1, d, t.q, e, t.r);
	// the low unit of a two's complement value is its value mod 2^mcl::UnitBitSize
	Unit di = d1[0] + im.lowM * ud;
	Unit ei = e1[0] + im.lowM * ue;
	Unit sd = ud - ((im.Mi * di) & Unit(mcl::inv::MASK));
	Unit se = ue - ((im.Mi * ei) & Unit(mcl::inv::MASK));
	mulAddNonNeg<W>(d1, M, sd);
	mulAddNonNeg<W>(e1, M, se);
	shr<W>(d, d1);
	shr<W>(e, e1);
}

// v += M if v < 0
template<int W>
void addMifNeg(Unit *v, const Unit *M)
{
	const Unit m = signMask(v[W - 1]);
	Unit t[W];
	for (int i = 0; i < W; i++) t[i] = M[i] & m;
	mcl::bint::addT<W>(v, v, t);
}

// v in (-2M, M) -> [0, M) (negated if minus)
template<int W>
void normalize(const Unit *M, Unit *v, bool minus)
{
	addMifNeg<W>(v, M);
	if (minus) {
		Unit zero[W];
		mcl::bint::clearT<W>(zero);
		mcl::bint::subT<W>(v, zero, v);
	}
	addMifNeg<W>(v, M);
}

template<int N, int W>
void exec(const Param<N>& im, Unit *py, const Unit *px)
{
	mcl::inv::Sint eta = -1;
	Unit f[W], g[W], d[W], e[W];
	mcl::bint::copyT<W>(f, im.M);
	mcl::bint::copyT<N>(g, px);
	for (int i = N; i < W; i++) g[i] = 0;
	mcl::bint::clearT<W>(d);
	mcl::bint::clearT<W>(e); e[0] = 1;
	mcl::inv::Quad t;
	while (!mcl::bint::isZeroT<W>(g)) {
		Unit fLow = f[0] & Unit(mcl::inv::MASK);
		Unit gLow = g[0] & Unit(mcl::inv::MASK);
		eta = mcl::inv::divsteps_n_matrix(t, eta, fLow, gLow);
		update_fg<W>(f, g, t);
		update_de<N, W>(im, d, e, t);
	}
	normalize<W>(im.M, d, (f[W - 1] >> (mcl::UnitBitSize - 1)) != 0);
	mcl::bint::copyT<N>(py, d);
}

} // twos

// twos::Param<N> of p for N = 4, 6 (initInvMod); llvm_invMod takes it as im
twos::Param<4> g_im4;
twos::Param<6> g_im6;
template<int N> const twos::Param<N>& getIm();
template<> const twos::Param<4>& getIm<4>() { return g_im4; }
template<> const twos::Param<6>& getIm<6>() { return g_im6; }
const uint64_t *invModPara() { return Fp::getOp().N == 4 ? (const uint64_t*)&g_im4 : (const uint64_t*)&g_im6; }
// mcl::inv::InvModT<N> of p (the signed-limb version of mcl)
mcl::inv::InvModT<4> g_mim4;
mcl::inv::InvModT<6> g_mim6;

// returns false if N is not 4 or 6 (invMod is skipped)
bool initInvMod()
{
	const fp::Op& op = Fp::getOp();
	switch (op.N) {
	case 4: return twos::initParam(g_im4, op.mp) && mcl::inv::init(g_mim4, op.mp);
	case 6: return twos::initParam(g_im6, op.mp) && mcl::inv::init(g_mim6, op.mp);
	default: return false;
	}
}

// mcl::inv::exec<N> (signed62) with the signature of llvm_invMod (im is ignored)
void mclInv(uint64_t *y, const uint64_t *x, const uint64_t *)
{
	if (Fp::getOp().N == 4) mcl::inv::exec<4>(g_mim4, y, x); else mcl::inv::exec<6>(g_mim6, y, x);
}

// the C++ versions with the signature of llvm_invMod (im is ignored; g_im<N>
// is used): twos = twos::exec<N, W> with W of im.wide (what mcl::inv::exec
// uses), wide = W = N + 1 always (the cost of the wider state)
template<int N, int W>
void invModW(uint64_t *y, const uint64_t *x, const uint64_t *) { twos::exec<N, W>(getIm<N>(), y, x); }
void invModTwos(uint64_t *y, const uint64_t *x, const uint64_t *im)
{
	if (Fp::getOp().N == 4) {
		if (g_im4.wide) invModW<4, 5>(y, x, im); else invModW<4, 4>(y, x, im);
	} else {
		if (g_im6.wide) invModW<6, 7>(y, x, im); else invModW<6, 6>(y, x, im);
	}
}
void invModWide(uint64_t *y, const uint64_t *x, const uint64_t *im)
{
	if (Fp::getOp().N == 4) invModW<4, 5>(y, x, im); else invModW<6, 7>(y, x, im);
}

// W : the number of units of f, g, d, e (N or N + 1 (im.wide))
template<int N, int W>
void checkInvModTW()
{
	using namespace mcl::inv;
	const twos::Param<N>& im = getIm<N>();
	const uint64_t *pim = (const uint64_t*)&im;
	const fp::Op& op = Fp::getOp();
	cybozu::XorShift rg;
	// 1. divsteps against mcl::inv::divsteps_n_matrix
	{
		const struct { const char *name; DivstepsOp f; } tbl[] = { { "llvm", llvm_inv_divsteps }, { "llvm_br", llvm_inv_divsteps_br } };
		for (int i = 0; i < 10000; i++) {
			Sint eta = Sint(rg.get32() % 200) - 100;
			Unit f = (rg.get64() & MASK) | 1;
			Unit g = rg.get64() & MASK;
			if (i % 100 == 0) g = 0;
			if (i % 100 == 1) g >>= rg.get32() % mcl::inv::modL;
			Quad t;
			Sint eta1 = divsteps_n_matrix(t, eta, f, g);
			for (const auto& e : tbl) {
				if (!e.f) continue;
				uint64_t t2[4];
				uint64_t eta2 = e.f(t2, uint64_t(eta), f, g);
				if (eta2 != uint64_t(eta1) || t2[0] != t.u || t2[1] != t.v || t2[2] != t.q || t2[3] != t.r) {
					fprintf(stderr, "ERR invMod divsteps %s i=%d\n", e.name, i);
					exit(1);
				}
			}
		}
	}
	// 2. update_fg / update_de on the states of the actual loop (twos::exec)
	if (llvm_inv_update_fg && llvm_inv_update_de) {
		for (int i = 0; i < 300; i++) {
			Fp xf;
			xf.setByCSPRNG(rg);
			const Unit *x = (const Unit*)&xf;
			Sint eta = -1;
			Unit f[W], g[W], d[W], e[W];
			mcl::bint::copyT<W>(f, im.M);
			mcl::bint::copyT<N>(g, x);
			for (int j = N; j < W; j++) g[j] = 0;
			mcl::bint::clearT<W>(d);
			mcl::bint::clearT<W>(e); e[0] = 1;
			while (!mcl::bint::isZeroT<W>(g)) {
				Quad t;
				eta = divsteps_n_matrix(t, eta, f[0] & MASK, g[0] & MASK);
				const uint64_t tv[4] = { t.u, t.v, t.q, t.r };
				Unit f2[W], g2[W], d2[W], e2[W];
				mcl::bint::copyT<W>(f2, f);
				mcl::bint::copyT<W>(g2, g);
				mcl::bint::copyT<W>(d2, d);
				mcl::bint::copyT<W>(e2, e);
				twos::update_fg<W>(f, g, t);
				llvm_inv_update_fg(f2, g2, tv);
				if (memcmp(f, f2, sizeof(f)) != 0 || memcmp(g, g2, sizeof(g)) != 0) {
					fprintf(stderr, "ERR invMod update_fg i=%d\n", i);
					exit(1);
				}
				twos::update_de<N, W>(im, d, e, t);
				llvm_inv_update_de(d2, e2, tv, pim);
				if (memcmp(d, d2, sizeof(d)) != 0 || memcmp(e, e2, sizeof(e)) != 0) {
					fprintf(stderr, "ERR invMod update_de i=%d\n", i);
					exit(1);
				}
			}
		}
	}
	// 3. exec: twos::exec<N, W> == exec<N, N+1> == mcl::inv::exec (signed62) == llvm_invMod == llvm_invMod_br,
	// y < p and x y == 1 mod p
	const struct { const char *name; InvModOp f; } tbl[] = { { "wide", invModWide }, { "mcl", mclInv }, { "llvm", llvm_invMod }, { "llvm_br", llvm_invMod_br } };
	auto checkOne = [&](const Unit *x, const char *msg) {
		Unit y0[N], y1[N];
		twos::exec<N, W>(im, y0, x);
		for (const auto& e : tbl) {
			if (!e.f) continue;
			e.f(y1, x, pim);
			if (memcmp(y0, y1, sizeof(y0)) != 0) {
				fprintf(stderr, "ERR invMod exec %s %s\n", e.name, msg);
				exit(1);
			}
			// in place
			mcl::bint::copyT<N>(y1, x);
			e.f(y1, y1, pim);
			if (memcmp(y0, y1, sizeof(y0)) != 0) {
				fprintf(stderr, "ERR invMod exec in place %s %s\n", e.name, msg);
				exit(1);
			}
		}
		mpz_class mx, my;
		bool b;
		gmp::setArray(&b, mx, x, N);
		gmp::setArray(&b, my, y0, N);
		if (my >= op.mp || (mx != 0 && (mx * my) % op.mp != 1) || (mx == 0 && my != 0)) {
			fprintf(stderr, "ERR invMod verify %s\n", msg);
			exit(1);
		}
	};
	for (int i = 0; i < 10000; i++) {
		Fp xf;
		xf.setByCSPRNG(rg);
		checkOne((const Unit*)&xf, "random");
	}
	// edge cases: 0, 1, 2, p-1, p-2, (p-1)/2, 2^k, p-2^k, 2^k-1
	{
		const size_t L = gmp::getBitSize(op.mp);
		std::vector<mpz_class> vs = { 0, 1, 2, op.mp - 1, op.mp - 2, (op.mp - 1) / 2 };
		for (size_t k = 0; k < L; k++) {
			mpz_class t = mpz_class(1) << k;
			vs.push_back(t);
			vs.push_back(op.mp - t);
			vs.push_back(t - 1);
		}
		for (const mpz_class& v : vs) {
			Unit x[N];
			bool b;
			gmp::getArray(&b, x, N, v);
			if (!b) { fprintf(stderr, "checkInvMod getArray\n"); exit(1); }
			checkOne(x, "edge");
		}
	}
}

void checkInvMod()
{
	if (Fp::getOp().N == 4) {
		if (g_im4.wide) checkInvModTW<4, 5>(); else checkInvModTW<4, 4>();
	} else {
		if (g_im6.wide) checkInvModTW<6, 7>(); else checkInvModTW<6, 6>();
	}
}

// the best of rep runs of f() over n items, ns per item
template<class F>
static double timeBest(F f, size_t n, int rep = 20)
{
	double best = 1e30;
	for (int i = 0; i < rep; i++) {
		auto t0 = std::chrono::steady_clock::now();
		f();
		auto t1 = std::chrono::steady_clock::now();
		double t = std::chrono::duration<double, std::nano>(t1 - t0).count() / n;
		if (t < best) best = t;
	}
	return best;
}

// ns per call of update_fg / update_de on the states of the actual loops
// (300 random inputs; the copy of the state is subtracted): C++ twos (bint)
// and LLVM
template<int N, int W>
void invModUpdateBench()
{
	using namespace mcl::inv;
	const twos::Param<N>& im = getIm<N>();
	const uint64_t *pim = (const uint64_t*)&im;
	struct State { Unit f[W], g[W], d[W], e[W]; uint64_t t[4]; Quad q; };
	std::vector<State> ss;
	cybozu::XorShift rg;
	for (int i = 0; i < 300; i++) {
		Fp xf;
		xf.setByCSPRNG(rg);
		const Unit *x = (const Unit*)&xf;
		{
			State s;
			Sint eta = -1;
			mcl::bint::copyT<W>(s.f, im.M);
			mcl::bint::copyT<N>(s.g, x);
			for (int j = N; j < W; j++) s.g[j] = 0;
			mcl::bint::clearT<W>(s.d);
			mcl::bint::clearT<W>(s.e); s.e[0] = 1;
			while (!mcl::bint::isZeroT<W>(s.g)) {
				eta = divsteps_n_matrix(s.q, eta, s.f[0] & MASK, s.g[0] & MASK);
				s.t[0] = s.q.u; s.t[1] = s.q.v; s.t[2] = s.q.q; s.t[3] = s.q.r;
				ss.push_back(s);
				twos::update_fg<W>(s.f, s.g, s.q);
				twos::update_de<N, W>(im, s.d, s.e, s.q);
			}
		}
	}
	const size_t n = ss.size();
	std::vector<State> w(ss);
	double tCopy = timeBest([&]{ for (size_t i = 0; i < n; i++) w[i] = ss[i]; }, n);
	double tFg = timeBest([&]{ for (size_t i = 0; i < n; i++) { w[i] = ss[i]; twos::update_fg<W>(w[i].f, w[i].g, w[i].q); } }, n) - tCopy;
	double tDe = timeBest([&]{ for (size_t i = 0; i < n; i++) { w[i] = ss[i]; twos::update_de<N, W>(im, w[i].d, w[i].e, w[i].q); } }, n) - tCopy;
	double tFgL = 0, tDeL = 0;
	if (llvm_inv_update_fg && llvm_inv_update_de) {
		tFgL = timeBest([&]{ for (size_t i = 0; i < n; i++) { w[i] = ss[i]; llvm_inv_update_fg(w[i].f, w[i].g, w[i].t); } }, n) - tCopy;
		tDeL = timeBest([&]{ for (size_t i = 0; i < n; i++) { w[i] = ss[i]; llvm_inv_update_de(w[i].d, w[i].e, w[i].t, pim); } }, n) - tCopy;
	}
	printf("update ns/call (W=%d, %.1f iterations/exec): %-14s %8s %8s\n", W, n / 300.0, "", "twos", "llvm");
	printf("%-53s %8.2f %8.2f\n", " update_fg", tFg, tFgL);
	printf("%-53s %8.2f %8.2f\n", " update_de", tDe, tDeL);
}

// latency (a serial chain x = inv(x) + 1; the +1 keeps the inputs from
// alternating between two values so that the branch predictor does not learn
// the divsteps pattern) and throughput (4 independent chains) of the C++
// versions (twos = twos::exec<N, W> of im.wide, wide = W = N + 1)
// and the LLVM versions
void invModBench()
{
	const uint64_t *pim = invModPara();
	const struct { const char *name; InvModOp f; } tbl[] = { { "twos", invModTwos }, { "wide", invModWide }, { "mcl", mclInv }, { "llvm", llvm_invMod }, { "llvm_br", llvm_invMod_br } };
	printf("invMod: base = twos (C++ two's complement, W=%d); mcl = mcl::inv::exec (signed62)\n", Fp::getOp().N == 4 ? (g_im4.wide ? 5 : 4) : (g_im6.wide ? 7 : 6));
	printf("%-7s %-11s %15s %15s %15s %15s %15s\n", "op", "mode", "twos", "wide", "mcl", "llvm", "llvm_br");
	cybozu::XorShift rg;
	const size_t an = 4;
	Fp x0[an];
	for (size_t k = 0; k < an; k++) x0[k].setByCSPRNG(rg);
	const size_t loop = 200000;
	for (size_t P = 1; P <= an; P += an - 1) {
		std::vector<double> v;
		for (const auto& e : tbl) {
			if (!e.f) {
				v.push_back(0);
				continue;
			}
			uint64_t a[an][8];
			for (size_t k = 0; k < an; k++) memcpy(a[k], &x0[k], sizeof(a[k]));
			InvModOp f = e.f;
			v.push_back(measure([&](size_t k) { f(a[k], a[k], pim); a[k][0]++; }, P, loop));
			volatile uint64_t sink = a[0][0]; (void)sink;
		}
		printRow("invMod", P == 1 ? "latency" : "throughput", v);
	}
	if (Fp::getOp().N == 4) {
		if (g_im4.wide) invModUpdateBench<4, 5>(); else invModUpdateBench<4, 4>();
	} else {
		if (g_im6.wide) invModUpdateBench<6, 7>(); else invModUpdateBench<6, 6>();
	}
}

int main(int argc, char *argv[])
{
	int mode;
	cybozu::Option opt;
	opt.appendOpt(&mode, TEST_MODE | BENCH_MODE, "mode", ": test(1), bench(2), both(3), default(3)");
	opt.appendHelp("h");
	if (!opt.parse(argc, argv)) {
		opt.usage();
		return 1;
	}
	const char *pStr = (const char*)llvm_get_prime();
	printf("p=%s\n", pStr);
	Fp::init(pStr, 1, 1);
	// safegcd inverse (N = 4, 6 only)
	if (!initInvMod()) {
		printf("invMod: N=%zd is not supported, skip\n", Fp::getOp().N);
		return 1;
	}
	if (mode & TEST_MODE) {
		checkInvMod();
		printf("test ok\n");
	}
	if (mode & BENCH_MODE) invModBench();
	return 0;
}
